name: crs.pics

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: "crs"
      POSTGRES_PASSWORD: "crs"
      POSTGRES_DB: "crs-pics"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
      target: hot-reload
    command: -build="sleep 3 && go build -o /build main.go" -command="/build/main" -log-prefix=false
    volumes:
      - ./backend:/app:ro
    ports:
      - "3000:3000"

volumes:
  postgres_data: